import 'package:hive/hive.dart';

part 'hive_models.g.dart'; // This file will be generated by `flutter packages pub run build_runner build`

@HiveType(typeId: 0)
class Nameplate extends HiveObject {
  @HiveField(0)
  Product? product;

  @HiveField(1)
  Manufacturer? manufacturer; // Manufacturer of the nameplate/overall product system

  Nameplate({this.product, this.manufacturer});
}

@HiveType(typeId: 1)
class Product extends HiveObject {
  @HiveField(0)
  String? uriOfTheProduct;

  @HiveField(1)
  String? manufacturerProductType;

  @HiveField(2)
  String? orderCodeOfManufacturer;

  @HiveField(3)
  String? productArticleNumberOfManufacturer;

  @HiveField(4)
  String? serialNumber;

  @HiveField(5)
  int? yearOfConstruction; // Assuming year is an integer

  @HiveField(6)
  DateTime? dateOfManufacture; // Using DateTime for dates

  @HiveField(7)
  String? countryOfOrigin;

  @HiveField(8)
  String? manufacturerProductDesignation;

  @HiveField(9)
  String? manufacturerProductRoot;

  @HiveField(10)
  String? manufacturerProductFamily;

  @HiveField(11)
  Manufacturer? manufacturer; // Manufacturer specifically for this product

  @HiveField(12) // New field for Markings within Product
  Markings? markings; // Markings for this product

  Product({
    this.uriOfTheProduct,
    this.manufacturerProductType,
    this.orderCodeOfManufacturer,
    this.productArticleNumberOfManufacturer,
    this.serialNumber,
    this.yearOfConstruction,
    this.dateOfManufacture,
    this.countryOfOrigin,
    this.manufacturerProductDesignation,
    this.manufacturerProductRoot,
    this.manufacturerProductFamily,
    this.manufacturer,
    this.markings, // Added to constructor
  });
}

@HiveType(typeId: 2)
class Manufacturer extends HiveObject {
  @HiveField(0)
  String? uniqueFacilityIdentifier;

  @HiveField(1)
  String? manufacturerName;

  Manufacturer({this.uniqueFacilityIdentifier, this.manufacturerName});
}

@HiveType(typeId: 3) // New HiveType for Markings
class Markings extends HiveObject {
  @HiveField(0)
  String? markingName;

  @HiveField(1)
  String? designationOfCertificateOrApproval;

  @HiveField(2)
  DateTime? issueDate;

  @HiveField(3)
  DateTime? expiryDate;

  @HiveField(4)
  String? markingAdditionalText;

  @HiveField(5)
  String? markingFile; // Assuming this is a path or URL to a file

  Markings({
    this.markingName,
    this.designationOfCertificateOrApproval,
    this.issueDate,
    this.expiryDate,
    this.markingAdditionalText,
    this.markingFile,
  });
}
